import Head from "next/head";
import { homeData, aboutMe, workItemData } from "../components/data";
import WorkItem from "../components/WorkItem";
import Image from "next/image";
import { BsFillMoonStarsFill, BsSunFill } from "react-icons/bs";
import {
  AiFillInstagram,
  AiFillTwitterCircle,
  AiFillLinkedin,
  AiFillGithub,
} from "react-icons/ai";
import Link from "next/link";
import { useState } from "react";

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);

  return (
    <div className={darkMode ? "dark min-h-screen" : "min-h-screen"}>
      <Head>
        <title>Portfolio website template</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="bg-white px-10 md:px-20 lg:px-40 dark:bg-slate-800">
        {homeData.map((data, index) => (
          <section id="profile" className="min-h-screen mb-8" key={index}>
            <nav className="py-10 mb-12 flex justify-between">
              <Link href="#">
                <h1 className="text-xl cursor-pointer font-burtons dark:text-slate-200">
                  {data.pageTitle}
                </h1>
              </Link>
              <ul className="flex items-center">
                <li>
                  {!darkMode ? (
                    <BsFillMoonStarsFill
                      className="cursor-pointer"
                      onClick={() => setDarkMode(!darkMode)}
                    />
                  ) : (
                    <BsSunFill
                      className="cursor-pointer text-slate-200"
                      onClick={() => setDarkMode(!darkMode)}
                    />
                  )}
                </li>
                <li>
                  <button className="ml-4 mb-0 bg-sky-400 hover:bg-sky-500 text-white px-3 py-1 rounded">
                    Resume
                  </button>
                </li>
              </ul>
            </nav>

            <div id="personal-info" className="px-7 text-center">
              <h2 className="text-5xl text-sky-400 md:text-6xl">{data.name}</h2>
              <h3 className="text-2xl py-8 text-slate-900 dark:text-slate-200 md:text-3xl">
                {data.jobTitle}
              </h3>
              <p className="text-md leading-8 text-slate-700 dark:text-slate-400 md:text-xl md:max-w-3xl mx-auto">
                {data.intro}
              </p>
            </div>
            <div
              id="social-icons"
              className="flex justify-center py-6 gap-10 mb-20"
            >
              <AiFillGithub className="text-3xl cursor-pointer text-slate-600 dark:text-slate-400 dark:hover:text-sky-400 hover:text-sky-400" />
              <AiFillLinkedin className="text-3xl cursor-pointer text-slate-600 dark:text-slate-400 dark:hover:text-sky-400 hover:text-sky-400" />
              <AiFillInstagram className="text-3xl cursor-pointer text-slate-600 dark:text-slate-400 dark:hover:text-sky-400 hover:text-sky-400" />
              <AiFillTwitterCircle className="text-3xl cursor-pointer text-slate-600 dark:text-slate-400 dark:hover:text-sky-400 hover:text-sky-400" />
            </div>
            <div
              id="profile-pic"
              className="relative mx-auto bg-gray-800 w-60 h-60 md:w-80 md:h-80 rounded-full overflow-hidden"
            >
              <Image
                src={data.profilePic}
                alt="profile-pic"
                layout="fill"
                objectFit="cover"
              />
            </div>
          </section>
        ))}

        {aboutMe.map((data, index) => (
          <section id="aboutMe" className="my-20" key={index}>
            <h2 className="font-bold text-2xl dark:text-slate-200">
              {data.title}
            </h2>
            <p className="leading-7 dark:text-slate-400">{data.description}</p>
          </section>
        ))}

        <section id="projects">
          <h2 className="text-2xl font-bold mb-4 dark:text-slate-200">
            Portfolio
          </h2>
          <div className="flex flex-col gap-4 pb-8 lg:flex-row lg:flex-wrap">
            <WorkItem data={workItemData} />
          </div>
        </section>
      </main>
    </div>
  );
}
